### ISSUE TITLE
Request adoption

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/jenkins_ynh#27]
I'm giving up that app that I don't use anymore.
Considering the current version works well.

Updating the app furthermore confront to the fucking cli protocol (that changed AGAIN !) and now request for an authentication.
https://jenkins.io/doc/book/managing/cli/#using-the-cli-client

Whomever is willing to take back this app is welcome. Just ask for it.

**Comment by softinio** [comment]
Whats the process for adopting this project? Any handover possible as part of it?

**Comment by maniackcrudelis** [comment]
Hi @softinio

Since I gave up that app a long time ago and I'm not working on that project anymore for almost as long, I was expecting someone else to answer you on that one...

As far as I know, this app is still unmaintained, so you would be welcome to take care of it.
I have no idea what the process is anymore, I guess you could start by cloning it and working on it if there's anything to fix. Then someone would give you permission on the repo. (I can't do it myself)

Just tried and the CLI protocol seems to work fine on the last version of the app.

@YunoHost-Apps/apps-group some help would be needed here.

**Comment by tituspijean** [comment]
> As far as I know, this app is still unmaintained

All the commits since 2020-06-20 would like to disagree. 😛 I guess we did not make time for officially assigning a new maintainer, and it falls into the "someone eventually takes care of it" category (which is risky, I concede).

> Whats the process for adopting this project? Any handover possible as part of it?

I did not actually find the proper process, assigning maintainership is simply updating the manifest file. I guess you are welcome in making PRs to fix it or upgrade it whenever a new version of Jenkins is available. If we see you are consistent in your contributions we can give you extended rights to handle PRs yourself and officially assign the app to you.

@yalh76, it seems you have been quite consistent in maintaining the app in the past few months. What's your take on this?

**Comment by yalh76** [comment]
Fully agree, @softinio, we let you do some regular PR on this app, and when you are ready we will give you extened rights on this repository. If you have some questions, don't hesistate to contact us in the application chat room https://yunohost.org/en/chat_rooms

**Comment by softinio** [comment]
Thanks all for being so welcoming to my interest. Unfortunately I have decided not to proceed at this time with this interest as my priorities have changed.
